### ISSUE TITLE
문서가 업데이트 된 이후 틀의 업데이트시 반영이 안되는 오류

### ISSUE THREAD

**Issue by qlido** [Team-INSERT/BUMAWIKI_WEB_V2#22]
### 🐞 Describe

문서가 업데이트 된 이후 틀의 업데이트시 반영이 안되는 요류

### 🌏 Environment

모든 환경

### 🙋🏻 More

고쳐주세요

**Comment by Ubinquitous** [comment]
만약 프론트엔드단에서 revalidate를 처리하게 된다면, 틀을 업데이트했을 경우 해당 틀을 include하고있는 문서를 모두 찾아야합니다. 물리적으로 어렵기도 하고, 이렇게 된다면 새로운 문서에 들어갈 때마다 revalidate된 틀을 가지고 오는지 확인해야합니다. 
SSG로는 프론트엔드만으로 어려운 일인데, 어쩌면 SSG를 유지하면서 이를 해결하는 새로운 방법은 없을까요?
