### ISSUE TITLE
httpClient 관련 질문

### ISSUE THREAD

**Issue by Ubinquitous** [Team-INSERT/BUMAWIKI_WEB_V2#3]
### ❓ Question
@J1min 안녕하세요! 코드 리팩토링 도중 궁금한 점이 생겨 질문드립니다.
[링크](https://github.com/Original-Gimchi/BUMAWIKI_WEB_V2/blob/refactor/http-client/lib/httpClient/index.tsx)
http-client를 사용할 때에, parameter로 받은 값을 어떻게 쿼리문에 작성할 수 있나요?
29번 라인 ~ 34번 라인의 getById method처럼, /:id로 표기하고 request config을 통해 사용하면 되는건가요?
혹은 직접 템플릿 리터럴을 통해 메서드를 적용해야 하나요?

\+ 쿼리도 동일하게 다음과 같이 사용할 수 있는지 궁금합니다.
```ts
getByQuery(query, requestConfig?: AxiosRequestConfig) {
	return this.api.get(`/?page=${query}`, {
		...HttpClient.clientConfig,
		...requestConfig,
	})
}
```

**Comment by J1min** [comment]
네 말씀하신 것처럼 getById를 사용하면 됩니다~
아래와 같이 requestConfig에 id params만 넘겨주시면 사용하실 수 있습니다.

```tsx
const useMember = (memberId: number) => {
  const { openToast } = useOverlay();
  const { data } = useQuery<Member>(
    [KEY.MEMBER],
    () =>
      httpClient.member
        .getById({ params: { id: memberId } })
        .then((r) => r.data)
        .catch(() => openToast("유저 정보를 불러오지 못했습니다.")),
    {
      enabled: !!memberId,
    },
  );
  return { data: data || fixture.user };
};
```

이렇게 사용할 수 있는 이유는 아래의 함수를 사용하였기 때문입니다!
/: 로 split 후 /: 뒤에 있는 인자 (위의 예시에서는 id 겠네요) 를 requestConfig parmas에서 꺼내온 후, paramParsedUrl에 붙여주는 로직입니다. 이를 응용한다면 id 이외의 이름으로도 사용할 수 있습니다. 
혹여나 이해가 안되신다면 slack DM 부탁드릴게요~

```tsx
export const requestInterceptors = (requestConfig: AxiosRequestConfig) => {
  
  const urlParams = requestConfig.url?.split("/:") || [];
  if (urlParams.length < 2) return requestConfig;

  const paramParsedUrl = urlParams
    ?.map((paramKey) => {
      return requestConfig.params[paramKey];
    })
    .join("/");

  urlParams?.forEach((paramKey: string) => {
    delete requestConfig.params[paramKey];
  }, {});

  return {
    ...requestConfig,
    url: paramParsedUrl,
  };
};
```

**Comment by Ubinquitous** [comment]
인터셉터의 존재를 잊고 있었네요! 정말 가독성 좋고 효율적인 구문같습니다!!
답변주셔서 감사합니다😄
