### ISSUE TITLE
헤더 UX 개선

### ISSUE THREAD

**Issue by 5ewon** [Team-INSERT/BUMAWIKI_WEB_V2#30]
### ✨ Describe

헤더에서 클릭 가능한 항목이 아님에도 호버시 헤더가 확장되어 불편함을 겪는 유저가 많습니다.
호버 영역을 조정 => 헤더 확장 통제
필요 호버 시간연장 => 불필요한 헤더 확장 방지

### ✅ Tasks

호버 감지 영역을 헤더바 전체에서 해당 텍스트 영역 정도로 줄이기.
마우스 호버시 바로 확장되는게 아니라 일정 시간동안 호버해야 확장되도록 로직 변경하기.

**Comment by J1min** [comment]
호버 영역 조정 아주 좋습니다~
혹시 
> 헤더에서 클릭 가능한 항목이 아님에도 호버시 헤더가 확장되어 불편함을 겪는 유저가 많습니다.

의 근거가 따로 있는지 궁금합니다!(추궁하는거 아님) 고객 조사를 어디서 하시는지 궁금해서요 😁

**Comment by 5ewon** [comment]
위와 같은 고객 의견들을 계획하에 조사하진 않았습니다.
허나 요청사항을 정리하면,
대상은 (주로)2학년 이용자들,
방식은 주로 구두로 요청하였습니다.

서비스의 주 이용 고객의 주된 사용방식을 통해 유추해볼 수 있는 경우로,
대부분 노트북을 통해 서비스를 이용했으며  터치패드를 사용하는 경우가 많습니다.
터치패드로 조작시 조작이 정밀하지 못해 원치 않게 헤더바가 확장되어 화면을 가리는 경우가 잦았습니다.
그리하여 불편을 겪는 고객이 많아져 그나마 접근이 좋은 2학년 학생들이 요청을 한 것으로 유추됩니다.

**Comment by J1min** [comment]
그렇군요~~ 감사합니다!!

**Comment by 5ewon** [comment]
수정 완료되었습니다.
