### ISSUE TITLE
학생 조회 UX 개선

### ISSUE THREAD

**Issue by jacobhboy** [Team-INSERT/BUMAWIKI_WEB_V2#33]
### ✨ Describe

학생 조회 페이지에서 별도의 오로지 학년의 구분으로만 학생들이 쭉 나오게 됩니다. 라디오 버튼으로 학년을 분리한다면 더 깔끔해 보일 것 같습니다.

### ✅ Tasks

- [x]  학생 조회 페이지에서 기수별로 라디오 버튼으로 조회

### 🙋🏻 More

다른 것들도 분리하는게 좋아보입니다 ~

**Comment by Ubinquitous** [comment]
https://github.com/Team-INSERT/BUMAWIKI_WEB_V2/commit/35985b2e4f7e99a7c8b2569d5f82f2146abb4f68

**Comment by Ubinquitous** [comment]
완료햇습니다
<img width="1023" alt="스크린샷 2023-07-24 오후 9 39 13" src="https://github.com/Team-INSERT/BUMAWIKI_WEB_V2/assets/102154880/332aab65-1545-4ce3-8752-e2d04280fb93">
