### ISSUE TITLE
외부 IP에서는 부마위키 접근 불가능한건가요?

### ISSUE THREAD

**Issue by enbraining** [Team-INSERT/BUMAWIKI_WEB_V2#46]
🙋🏻 할 말
원레는 부마위키 접근 가능했는데 어떤 이유인지는 모르지만 접속이 불가능합니다.
혹시 오류적인 부분인가요? 아니면 의도적인건가요?

**Comment by Ubinquitous** [comment]
호스팅 서버 변경 작업을 진행중이라 잠깐 서버를 닫아두었습니다
다시 디플로이되면 코멘트 남겨드리겠습니다!

**Comment by Ubinquitous** [comment]
deploy되었습니다! 감사합니다 좋은하루보내세요😄
